service: emailess

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  region: ${env:REGION}
  apiKeys:
    - EmailServiceKeys
    - ${env:STAGE}-EmailServiceKeys
  usagePlan:
    throttle:
      burstLimit: 1
      rateLimit: 1  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:*
      Resource: "*"      
  
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 
          path: '{proxy+}'
          method: any
          private: true 

plugins:
  - serverless-offline
  - serverless-dotenv-plugin